AndelaOSP/wire-api

db/dumps/wire-dev-20170909.sql
routes/incidents.js
services/incidents.js

feat: get specific incident

---

routes/notes.js
services/notes.js

feat: endpoint for adding incident note

---

routes/incidents.js
routes/notes.js
services/notes.js

feat: endpoint to get all notes

---

services/incidents.js

Add joins for both fetch one incident and fetch many incidents to include status in the response.
Closes #13 
Signed-off-by: Mnickii <caroline.nkirote@andela.com>

ch: Update get incidents/incident endpoints to include status

---

routes/notes.js
services/notes.js

feat: add replies to notes

---

db/dumps/raw-migrations-201709091100.sql
routes/incidents.js
services/incidents.js

feat: add/get sentiments for an incident

---

routes/notes.js
services/notes.js

feat: get all replies to a note

---

db/dumps/wire-20170911.sql
db/dumps/wire-dev-20170910.sql
routes/incidents.js
services/incidents.js

feat: add locations endpoint + cleanup

---

db/dumps/wire-20170911.sql
routes/incidents.js
services/incidents.js

for the following endpoints
- getting incident categories
- getting incident category levels
- adding incident categories
closes #27

feat: adding/getting incident categories

---

README.md

Add Authentication guidelines to README

---

README.md

ch(add-screenshots-to-readme)

---

.env.example
.eslintrc
db/config.js
package.json
routes/auth.js
yarn.lock

Sets up Airbnb code style linting

Setup linting 

---

.gitignore
README.md

Updates the readme and ignores package-lock.json
Update README to take new set up
The readme
N/A
N/A
[153475280](https://www.pivotaltracker.com/n/projects/2117172/stories/153475280)
N/A

#153475280 Update README.md

---

server/controllers/index.js
server/controllers/statuses.js
server/routes/index.js
server/seeders/status.js

Creates endpoints for statuses
Initialises DB with pre-existing statuses.
Allows admin to create, view existing statuses and update a status.
Postman: routes specified on the routes/index file
No additional status needs to be created though the post endpoint works.
[153356999](https://www.pivotaltracker.com/n/projects/2117172/stories/153356999)

#153356999 Feat:create statuses controller

---

server/controllers/incidents.js
server/controllers/index.js
server/controllers/levels.js
server/controllers/locations.js
server/controllers/statuses.js
server/routes/index.js
server/seeders/levels.js

Creates endpoints for levels
Initialises DB with pre-existing levels.
Allows admin to create, view existing levels and update a level.
Postman: routes specified on the routes/index file
No additional levels need to be created but the post exists for scalability
[153356982](https://www.pivotaltracker.com/n/projects/2117172/stories/153356982)

153356982 Feat: create levels controller

---

server/controllers/incidents.js
server/controllers/index.js
server/controllers/notes.js
server/routes/index.js

Add notes controller to power the note API routes.
- Add notes API routes
- Include notes on GET incidents
- Add a notes controller with all the route methods
..controllers/notes.js
```npm run start:dev ```, then use the notes API routes on postman
Notes belong to Incidents
#153356848

#153356848 Add notes controller

---

server/controllers/categories.js
server/controllers/index.js
server/controllers/notes.js
server/models/categories.js
server/routes/index.js
server/seeders/categories.js

Create a categories controller to power the Categories API routes
-Add categories API routes
-Add all categories methods including post, get, update
-Update Categories model to include "visible" column
-Add a categories seeder
..controllers/categories.js
```npm run start:dev``` then test the categories' API routes on postman
-An Incident belongs to a particular Category.
-A Category belongs to a particular Level
[153356964](https://www.pivotaltracker.com/story/show/153356964)
N/A

#153356964 Feat: Add categories controller

---

server/controllers/index.js
server/controllers/notes.js
server/controllers/replies.js
server/routes/index.js

Create Replies controller
- Add replies api routes
- Add replies methods: post, get, update, delete
- Update Notes GET method to include replies & validate post
Postman with routes defined for replies
N/A
[153356913](https://www.pivotaltracker.com/n/projects/2117172/stories/153356913)

153356913 Feat: Add Replies controller

---

server/migrations/20171120042555-create-roles.js
server/migrations/20171120042556-create-users.js
server/migrations/20171120042634-create-incidents.js
server/migrations/20171120042655-create-notes.js
server/migrations/20171120042706-create-replies.js
server/models/roles.js
server/models/users.js

Refactors users model and adds a separate roles model
- create roles model
- refactor user models
- refactor other models that take userId(foreignKey)
../models/users
Postman
N/A
[154242125](https://www.pivotaltracker.com/n/projects/2117172/stories/154242125)

#154242125 Feat: Refactor users model

---

server/controllers/index.js
server/controllers/roles.js
server/migrations/20180110150953-create-incident-level.js
server/models/roles.js
server/routes/index.js
server/seeders/roles.js

Adds roles services
- update model & migrations
- create seeders
- add methods for endpoints
- add routes
../controllers/roles
`npm run start:dev` then test the routes API routes on postman
N/A
[154244059](https://www.pivotaltracker.com/n/projects/2117172/stories/154244059)
N/A

#154244059 feat: roles controller

---

server/seeders/locations.js

-Add locations.js seeder
-Add locations.js seeder
[154353206](https://www.pivotaltracker.com/story/show/154353206)

ch(add locations seeders)

---

server/seeders/users.js

-Add users.js seeder
-Add users.js seeder
[#154353206](https://www.pivotaltracker.com/story/show/154353206)

#154353206 Add Users Seeder

---

Procfile
package.json
yarn.lock

Deploys API to Heroku
- add procfile to run script
- add scripts for deployment
[wire-api](https://wire-api.herokuapp.com/)
N/A
N/A
[154359943](https://www.pivotaltracker.com/n/projects/2117172/stories/154359943)
N/A

#154359943 chore: deploy to heroku

---

server/controllers/categories.js
server/controllers/incidents.js
server/controllers/levels.js
server/controllers/locations.js
server/controllers/statuses.js
server/migrations/20171120042634-create-incidents.js
server/models/categories.js
server/models/incidents.js
server/models/levels.js
server/routes/index.js

Allows filtering incidents
Creates a relationship between incidents & levels
Filter incidents by:
- Location
- Level
- Category
- Status
[Routes/index.js](https://github.com/AndelaOSP/wire-api/blob/ft-filter-incidents/server/routes/index.js)
Navigate through Routes/index to the filter routes. Test on Postman
N/A
[154221502](https://www.pivotaltracker.com/n/projects/2117172/stories/154221502)

#154221502 Feat: filter incidents

---

server/controllers/incidents.js
server/controllers/locations.js
server/migrations/20171120042457-create-locations.js
server/migrations/20171120042634-create-incidents.js
server/models/incidents.js
server/models/locations.js
server/seeders/locations.js

Add a Country column to Locations Model
-Add country column to locations migration
-Add country column to locations model
-Refactor locations controller to reflect changes
-Update locations seeder
[#154435277](https://www.pivotaltracker.com/story/show/154435277)

#154435277 chore: Refactor Location and Incident models

---

server/controllers/incidents.js

Locations validations
- check if location exists
- create if location does not exist
- assign incident to the new locationId/old existing ID
- rm unnecessary imports
[154663402](https://www.pivotaltracker.com/story/show/154663402)

#154663402 chore: validate locations

---

server/controllers/index.js
server/controllers/users.js
server/migrations/20171120042556-create-users.js
server/models/users.js
server/routes/index.js
server/seeders/users.js
server/services/users.js

POST endpoint to add new users
- add id to users model
- rename `name` column on seeders/migration
- create POST method as service
- add users POST route
- initialize role as USER
- Validation check for existing users
../routes/index.js
`npm run start:dev` then test the users route on postman
N/A
[153356892](https://www.pivotaltracker.com/story/show/153356892)

#153356892 feat: users services

---

server/controllers/incidents.js
server/controllers/locations.js
server/services/locations.js

locations service
- create locations services to reuse in controllers
- refactor incidents & locations controllers
[154921351](https://www.pivotaltracker.com/story/show/154921351)

#154921351 chore:add locations service file

---

server/controllers/incidents.js
server/migrations/20171120042634-create-incidents.js
server/migrations/20180205133536-create-witnesses.js
server/models/incidents.js
server/models/users.js
server/models/witnesses.js

creates witnesses model
- add relationships with other tables
(witnesses belong to incidents & users tables)
- rm witnesses column from incidents table
`npm run postinstall`
N/A
[154921984](https://www.pivotaltracker.com/story/show/154921984)
N/A

#154921984 feat: create witnesses model

---

server/migrations/20171120042634-create-incidents.js
server/models/assignees.js
server/models/incidents.js
server/models/users.js

Creates assignee associations for User and Incident models
-Add Assignee model
-Add assignee relations in User and Incident model (Incidents belong to assignees, Assignees are users)
```npm run postinstall```
N/A
[#154922122](https://www.pivotaltracker.com/story/show/154922122)

 #154922122 feat: Create an assignee model

---

package.json
server/controllers/incidents.js
server/migrations/20171120042457-create-locations.js
server/migrations/20171120042634-create-incidents.js
server/migrations/20171120042655-create-notes.js
server/migrations/20171120042706-create-chats.js
server/models/chats.js
server/models/incidents.js
server/models/locations.js
server/models/notes.js
server/seeders/locations.js

Updates model ids to cuids
- update model ids
- update migration ids
- update locations seeders
- test endpoints
- rm Alias for Assignees
None
[155587846](https://www.pivotaltracker.com/story/show/155587846)

#155587846 chore: update model ids to cuids

---

server/controllers/incidents.js
server/controllers/users.js
server/migrations/20171120042634-create-incidents.js
server/migrations/20180228152639-create-user-incidents.js
server/migrations/20180315113258-create-assignee-incidents.js
server/models/assigneeincidents.js
server/models/incidents.js
server/models/user-incidents.js
server/models/users.js
server/routes/index.js
server/services/locations.js

Refactor models between users and incidents: reporter and assignee 
N/A
**Fetching an Incident**
**Fetching a user**

Refactor Models

---

server/controllers/incidents.js
server/routes/index.js

Creates a search endpoint.
As a user, i should be able to search for incidents logged by querying either by description or subject of an incident.
[#issue23](https://github.com/AndelaOSP/wire-api/issues/23)
Run the project. 
On postman do a GET method on this endpoint `http://localhost:8000/api/search/incidents/` and add a query to it.
[#155969645](https://www.pivotaltracker.com/n/projects/2117172)

#155969645 feature: search endpoint

---

server/controllers/incidents.js

Update `update` method for incidents.

chore(update): Refactor incident update method

---

server/controllers/incidents.js

Fix date format
Request from the bot `dd-mm-yy`
[Place link to file here]()
N/A
N/A
[Place PT id here]()
N/A

fix: date format request

---

index.js

Signed-off-by: Mercy-Muchai <mercy.muchai@andela.com>
N/A
N/A
[Place link to file here]()
N/A
N/A
[Place PT id here]()
N/A

configure cors

---

server/controllers/chats.js
server/controllers/incidents.js
server/controllers/notes.js
server/migrations/20171120042655-create-notes.js
server/migrations/20171120042706-create-chats.js
server/models/chats.js
server/models/notes.js
server/models/users.js

Refactor notes and chats to use user's email vs userId
- refactor models and relationship
- refactor controllers to use email vs userId
[#156339568](https://www.pivotaltracker.com/story/show/156339568)

#156339568 feat: refactor chats & notes:

---

server/controllers/incidents.js

Updates search response to having includes.
[#156371231](https://www.pivotaltracker.com/n/projects/2117172)

chore : update search to have includes

---

.gitignore
server/models/chats.js
server/models/notes.js

Fix issue with email foreign key

Set target foreign Key

---

.gitignore
index.js
package.json
server/config/config.json
server/controllers/chats.js
server/controllers/incidents.js
server/controllers/levels.js
server/controllers/locations.js
server/controllers/notes.js
server/controllers/roles.js
server/controllers/statuses.js
server/controllers/users.js
server/migrations/20171120042655-create-notes.js
server/migrations/20171120042706-create-chats.js
server/models/chats.js
server/models/notes.js
server/models/users.js
server/seeders/users.js
yarn.lock

N/A
N/A
[Place link to file here]()
N/A
N/A
[Place PT id here]()
N/A

fix(res): Can't set headers after they are sent

---

.gitignore
index.js
package.json
server/config/config.json
server/controllers/chats.js
server/controllers/incidents.js
server/controllers/levels.js
server/controllers/locations.js
server/controllers/notes.js
server/controllers/roles.js
server/controllers/statuses.js
server/controllers/users.js
server/migrations/20171120042655-create-notes.js
server/migrations/20171120042706-create-chats.js
server/models/chats.js
server/models/notes.js
server/models/users.js
server/seeders/users.js
yarn.lock

Deployment

---

package.json
server/seeders/categories.js
server/seeders/incidents.js
server/seeders/locations.js
server/seeders/reporters.js
server/seeders/roles.js
server/seeders/status.js
server/seeders/users.js
server/seeders/witnesses.js

Add seed data for incidents
- create seeders for incidents, reporters & witnesses
`npm run postinstall`
[#156503898](https://www.pivotaltracker.com/story/show/156503898)

#156503898 chore: add incident seeders

---

.circleci/config.yml
.gitignore
.istanbul.yml
package.json
test/users.js

- configures test environment.
- configures test coverage.
- configures test scripts.
run ```npm test```
[#156502522](https://www.pivotaltracker.com/n/projects/2117172)

#156502522 (ch): set up test configurations

---

server/controllers/locations.js
server/routes/index.js
test/locations.js

-Adds tests to locations controllers.
[#156721006](https://www.pivotaltracker.com/n/projects/2117172)

#156721006 (ch): Add tests to locations controllers

---

server/controllers/chats.js
server/controllers/incidents.js
server/controllers/notes.js
test/chats.js

Add tests to chat controllers.
[#156687555](https://www.pivotaltracker.com/n/projects/2117172)

#156687555 chore:  Chats tests

---

test/notes.js

Adds tests to notes controllers.
[#156720981](https://www.pivotaltracker.com/n/projects/2117172)

#156720981 chore: Add notes tests

---

package.json
server/controllers/categories.js
server/controllers/chats.js
server/controllers/errorLogs.js
server/controllers/incidents.js
server/controllers/locations.js
server/controllers/notes.js
server/controllers/users.js
yarn.lock

slack-error-notify
- use [package](https://www.npmjs.com/package/slack-error-notify) on each method
[#157051861](https://www.pivotaltracker.com/story/show/157051861)

#157051861 feat: use package to log errors on incidents

---

server/controllers/chats.js
server/controllers/incidents.js
server/controllers/notes.js
server/controllers/users.js
server/migrations/20171120042556-create-users.js
server/models/locations.js
server/models/users.js
server/seeders/users.js

- Updates models: users belong to locations
- update relationship: users belong to locations
- update seeeders to match models
- update migrations
Files changed
`npm run postinstall` then `npm run start:dev`
It was important to have notifications per reported incident to notify the same location People. Users location will be checked to notify the same location People.
[#156804047](https://www.pivotaltracker.com/story/show/156804047)

#156804047 feat: users & locations' models relationship

---

server/controllers/users.js
test/users.js

Update body
- refactor tests
- update req.body structure

Chore: fix tests & update body

---

Makefile
docker/dev/api/Dockerfile
docker/dev/api/start.sh
docker/dev/database/Dockerfile
docker/dev/database/createdb.sql
docker/dev/docker-compose.yaml

Adds the docker files to dockerize the API, decouple the DB from the API and makefile to automate the environment creation a local dev environment using docker-compose for the backend (API and database).
Dockerizing the wire API and at the same time decoupling it from the database. Hence a result of 2 dockerfiles. As well as putting together a makefile that will automate the creation of a development work environment.
[Docker files](https://github.com/AndelaOSP/wire-api/tree/ch-local-dev-environment/docker/dev)
[Makefile](https://github.com/AndelaOSP/wire-api/blob/ch-local-dev-environment/Makefile)
Set the environment variable LOCAL_REPO_DIRECTORY to the location of this repo on your local machine. Then in the root folder of this repo, where the makefile is, run `make build`. that should …

Ch local dev environment

---

yarn.lock

Beta Merge

---

src/server/config/config.json

Fixes CI docker database connection issue.

fix(ci): fix ci docker connection issue

---

scripts/deploy.sh

Ch fix circleci docker builds

---

scripts/deploy.sh

This PR fixes the Ci Builds by introducing the following changes
- Change Google Compute Engine Zone
- Update kubectl commands to use namespace
- Change K8s Cluster name
- Remove error exit error

CH: circle ci docker deployment scripts

---

.dockerignore
scripts/deploy.sh

This PR adds CI pipeline to build and deploy wire-backend to k8s cluster once the PR has been merged to staging or master.
With the current implementation, the deployment process has been automated. This means when a release is merged to staging and master, the ci will build a Docker image, publish it to GCP container registry and update the k8s cluster with the recent image.
Completes #157974552

157974552 ci pipeline

---

Dockerfile

This task creates dockerfile in root directory.
The automated deploy job could file because it couldn't find the docker file in the root directory.
https://circleci.com/gh/AndelaOSP/wire-api/225
Auditing the automated CI&CD pipeline

move dockerfile to home directory

---

README.md

Move dockerfile to home directory

Fix docker 

---

README.md
src/server/controllers/incidents.js

Merges Develop into staging with the new bug fixes.

#chore: Add bug fixes into Staging.

---

src/server/controllers/incidents.js

Fixes incidents posts when witnesses are not available.

ch: Incident witnesses bug fix

---

src/server/controllers/incidents.js
src/server/helpers/findOrCreateUser.js
src/server/migrations/20171120042556-create-users.js
src/server/models/users.js
src/server/seeders/reporters.js
src/server/seeders/users.js
src/server/seeders/witnesses.js
src/templates/emailTemplate.html
src/test/users.js

- Add `slackId` to Incident responses and user model
[#159986059](https://www.pivotaltracker.com/story/show/159986059)
N/A

#159986059 CH: Add slackid to user model and incidents response

---

Dockerfile
scripts/migration.sh

Adds run migration to docker file
Updates weren't running migrations. When new models are added, changes aren't noticed.

Run migration in dockerfile

---

src/server/migrations/20171120042543-create-levels.js
src/server/seeders/levels.js

Fix issue where there was an `id` mismatch cause of the `auto-increment` property
[#160245385](https://www.pivotaltracker.com/story/show/160245385)
N/A

Chore fix issue with staging db

---

src/server/controllers/incidents.js
src/server/controllers/users.js
src/server/helpers/findOrCreateUser.js

Update an existing user's `slackId` when they create a new Incident
When a user is invited to WIRE their `slackId` is blank at first. So this task is about adding the user's `slackId` the database if and when they create an incident. 
- Clone this branch
- Create an incident using `wire-bot`
- Use a user who doesn't have a `slackId` in the database
- If the incident is created successfully then the `slackId` should be updated
[#160263840](https://www.pivotaltracker.com/story/show/160263840)
N/A

Chore update existing user slackId from new incident

---

src/server/controllers/incidents.js
src/test/incidents.js

Add much-needed tests for the Incidents controller
[#160233169](https://www.pivotaltracker.com/story/show/160233169)
N/A

Ch write tests for incidents controller 160233169

---

src/server/controllers/incidents.js
src/server/helpers/emailHelper.js
src/server/helpers/generateAssigneeOrCcdEmailBody.js
src/server/helpers/generateEmailBody.js
src/server/helpers/getUsernameFromEmail.js
src/server/middlewares/authentication.js

- Makes it possible for an Assignee or Ccd user to receive an email when they are assigned to an incident or CCD
- Clone `wire-front` and set it up
- Clone this branch and set it up
- Create an incident using `wire-bot`
- Then log in to `wire-front` as an admin
- Assign an incident to a user (doesn't matter if an admin or an assignee) 
- The user should receive an email
N/A
[#160347571](https://www.pivotaltracker.com/story/show/160347571)

Feature send assignee or ccd email 

---

src/server/controllers/incidents.js
src/server/helpers/listAssigneeIncidentsIncludes.js
src/server/middlewares/authentication.js
src/server/routes/index.js

- Make sure assignees can only see incidents they have been assigned
- Allow assignees to `cc` other users
[#160291760](https://www.pivotaltracker.com/story/show/160291760)
N/A

Chore implement various assignee auth features
